// src/components/LinkifiedText.tsx
'use client';

import { parseTextWithUrls } from '@/lib/utils/linkify';

export interface LinkifiedTextProps {
  text: string;
  className?: string;
}

export function LinkifiedText({ text = '', className = '' }: LinkifiedTextProps) {
  const segments = parseTextWithUrls(text);
  return (
    <span className={className}>
      {segments.map((segment, i) =>
        segment.type === 'url' ? (
          <a
            key={i}
            href={segment.value}
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-400 hover:text-blue-300 underline break-all"
          >
            {segment.value}
          </a>
        ) : (
          <span key={i}>{segment.value}</span>
        )
      )}
    </span>
  );
}

// src/lib/components/LinkifiedText.svelte
<script lang="ts">
  import { parseTextWithUrls } from '$lib/utils/linkify';

  interface Props {
    text: string;
    class?: string;
  }

  let { text = '', class: className = '' }: Props = $props();
  const segments = $derived(parseTextWithUrls(text));
</script>

<span class={className}>
  {#each segments as segment}
    {#if segment.type === 'url'}
      <a
        href={segment.value}
        target="_blank"
        rel="noopener noreferrer"
        class="text-blue-400 hover:text-blue-300 underline break-all"
      >
        {segment.value}
      </a>
    {:else}
      {segment.value}
    {/if}
  {/each}
</span>
